name: BVC Scraper Automatico

on:
  schedule:
    - cron: '0 19 * * 1-5' # 3:00 PM hora Caracas (Lunes a Viernes)
  workflow_dispatch:      # Bot√≥n para correrlo manualmente cuando quieras

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

     - name: Instalar dependencias del sistema Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libpng-dev libjpeg-dev libxtst6 libnss3 libatk-bridge2.0-0 libgtk-3-0

      - name: Instalar Librerias de R
        run: |
          Rscript -e 'install.packages(c("chromote", "rvest", "dplyr", "stringr", "readr"), dependencies = TRUE)'

      - name: Ejecutar Scraper
        run: Rscript script_bvc.R

      - name: Subir cambios a GitHub
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data_bvc_actual.csv
          git commit -m "Actualizacion automatica BVC $(date)" || echo "Sin cambios"
          git push