name: scraper

on:
  schedule:
    # Corre a las 2:00 PM Caracas (18:00 UTC) de lunes a viernes
    - cron: '0 18 * * 1-5'
  workflow_dispatch: # Esto reactiva el botón de "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar dependencias del sistema Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libpng-dev libjpeg-dev libxtst6 libnss3 libatk-bridge2.0-0 libgtk-3-0

      - name: Instalar Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Instalar Librerias de R
        run: |
          Rscript -e 'install.packages(c("chromote", "rvest", "dplyr", "stringr", "readr"), dependencies = TRUE)'

      - name: Ejecutar Scraper
        run: Rscript script_bvc.R

      - name: Subir cambios a GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data_bvc_actual.csv
          git commit -m "Actualización automática BVC" || echo "No hay cambios para subir"
          git push